import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { environment } from '../../environments/environment';
export interface PlaceOrderResponse {
  orderId: number;
  orderNumber: string; // Add this
}

export interface OrderPayload {
  customerId: string;
  customerName: string;
  customerEmail: string;
  address: string;
  phoneNumber: string;
  totalAmount: number;
  orderDate: string;
  orderItems: OrderItem[];
  // No need to send orderNumber from frontend - it will be generated by backend
}
export interface PlaceOrderRequest {
  customerId: number;
  items: OrderItem[];
  totalAmount: number;
  shippingAddress: string;
  customerName: string;
  customerEmail: string;
  phoneNumber: string;
}
export interface OrderItem {
  productId: number;
  productName: string;
  productPrice: number;
  quantity: number;
}
// Order Item DTO
export interface OrderItemConfirmationDto {
  orderItemId: number;
  productId: number;
  productName: string;
  productImageUrl: string;
  productPrice: number;
  quantity: number;
  productDescription: string;
  productSku: string;
  deliveryTimeSpan: string;
}

// Main Order Confirmation DTO
export interface OrderConfirmationDto {
  orderId: number;
  orderNumber: string;
  orderDate: string;
  status: number;
  customerName: string;
  customerEmail: string;
  shippingAddress: string;
  phoneNumber: string;
  totalAmount: number;
  items: OrderItemConfirmationDto[];
}
export interface OrderItemDetailDto{
  orderItemId:number;
  productId:number;
  productName:string;
  productImageUrl:string;
  productPrice:number;
  quantity:number;
  productDescription:string;
  nailSize: string;
}
export interface OrderResponse {
  orderId:number;
  orderNumber:string;
  orderDate:string;
  //status:string;
  status:number;
  totalAmount:number;
  totalItems:number;
  items:OrderItemDetailDto[];
}
export interface PaymentRequest {
  orderId: number;
  transactionId: string;
  paymentDate: string;
  paidAmount: number;
  paymentMethod: string; // 'UPI', 'COD', 'BANK_TRANSFER'
  status: string; // 'pending_verification', 'verified', 'failed'
  screenshotUrl?: string;
}

export interface PaymentResponse {
  paymentId: number;
  status: string;
  message: string;
}
export interface UpdateOrderPaymentRequest {
  orderId: number;
  paymentMethod: string;
  status: string;
}
@Injectable({
  providedIn: 'root'
})
export class OrderService {
  private baseUrl = environment.apiBaseUrl;

  constructor(private http: HttpClient) {}
// 1. Place New Order
  // placeOrder(orderPayload: any): Observable<any> {
  //   return this.http.post(this.baseUrl+ '/api/orders', orderPayload);
  // }
    // Update return type to include orderNumber
  placeOrder(orderPayload: OrderPayload): Observable<PlaceOrderResponse> {
    return this.http.post<PlaceOrderResponse>(this.baseUrl + '/api/orders', orderPayload);
  }
  getCustomerAllOrders(customerId:number):Observable<OrderResponse[]>{
    return this.http.get<OrderResponse[]>(`${this.baseUrl}/api/Customer/GetCustomerAllOrders/${customerId}`);
  }
   getOrderConfirmation(orderId:number):Observable<any[]>{
    return this.http.get<any[]>(`${this.baseUrl}/api/Customer/GetOrderConfirmation/${orderId}`);
  }
    // 2. Submit Payment Details (UPI/Bank Transfer)
  submitPayment(paymentData: PaymentRequest): Observable<PaymentResponse> {
    return this.http.post<PaymentResponse>(
      `${this.baseUrl}/api/Payments/SubmitPayment`,
      paymentData
    );
  }

    updateOrderPayment(orderId: number, paymentData: UpdateOrderPaymentRequest): Observable<any> {
    return this.http.put(
      `${this.baseUrl}/api/Orders/${orderId}/UpdatePayment`,
      paymentData
    );
  }
   // 5. Upload Payment Screenshot
  uploadPaymentScreenshot(file: File, orderId: number): Observable<any> {
    const formData = new FormData();
    formData.append('file', file);
    formData.append('orderId', orderId.toString());

    return this.http.post(
      `${this.baseUrl}/api/Payments/UploadScreenshot`,
      formData
    );
  }
   // 6. Verify Payment (Admin)
  verifyPayment(paymentId: number, isVerified: boolean, adminNotes?: string): Observable<any> {
    return this.http.post(
      `${this.baseUrl}/api/Payments/VerifyPayment`,
      {
        paymentId,
        isVerified,
        adminNotes
      }
    );
  }
   // 7. Get Payment Status
  getPaymentStatus(orderId: number): Observable<any> {
    return this.http.get(
      `${this.baseUrl}/api/Payments/Order/${orderId}/Status`
    );
  }
   prepareOrderData(cartItems: any[], customerInfo: any, totalAmount: number): PlaceOrderRequest {
    const orderItems: OrderItem[] = cartItems.map(item => ({
      productId: item.productId,
      productName: item.productName,
      productPrice: item.productPrice,
      quantity: item.quantity
    }));

    return {
      customerId: customerInfo.customerId,
      items: orderItems,
      totalAmount: totalAmount,
      shippingAddress: customerInfo.address,
      customerName: customerInfo.name,
      customerEmail: customerInfo.email,
      phoneNumber: customerInfo.phone
    };
  }
  // Get status text for display
  getStatusText(status: number): string {
    const statusMap: { [key: number]: string } = {
      0: 'Pending',
      1: 'Processing',
      2: 'Completed',
      3: 'Cancelled',
      4: 'Shipped',
      5: 'Delivered',
      6: 'Returned',
      7: 'Refunded',
      8: 'On Hold',
      9: 'Confirmed'
    };
    return statusMap[status] || 'Unknown';
  }

  // Get status class for CSS
  getStatusClass(status: number): string {
    const classMap: { [key: number]: string } = {
      0: 'bg-warning text-dark',
      1: 'bg-info text-white',
      2: 'bg-success text-white',
      3: 'bg-danger text-white',
      4: 'bg-primary text-white',
      5: 'bg-success text-white',
      6: 'bg-secondary text-white',
      7: 'bg-dark text-white',
      8: 'bg-warning text-dark',
      9: 'bg-success text-white'
    };
    return classMap[status] || 'bg-secondary text-white';
  }
}
