// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NailApi.Data;

#nullable disable

namespace NailApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250726082653_AddCustomerIdField")]
    partial class AddCustomerIdField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NailApi.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("nl_Categories", (string)null);
                });

            modelBuilder.Entity("NailApi.Models.CityMaster", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.HasIndex("DistrictId");

                    b.ToTable("nl_Cities", (string)null);

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityName = "City -1-D1",
                            DistrictId = 1
                        },
                        new
                        {
                            CityId = 2,
                            CityName = "City -2-D1",
                            DistrictId = 1
                        },
                        new
                        {
                            CityId = 3,
                            CityName = "City -3-D1",
                            DistrictId = 1
                        },
                        new
                        {
                            CityId = 4,
                            CityName = "City -4-D1",
                            DistrictId = 1
                        },
                        new
                        {
                            CityId = 5,
                            CityName = "City -1-D2",
                            DistrictId = 2
                        },
                        new
                        {
                            CityId = 6,
                            CityName = "City -2-D2",
                            DistrictId = 2
                        },
                        new
                        {
                            CityId = 7,
                            CityName = "City -3-D2",
                            DistrictId = 2
                        },
                        new
                        {
                            CityId = 8,
                            CityName = "City -4-D2",
                            DistrictId = 2
                        },
                        new
                        {
                            CityId = 9,
                            CityName = "City -1-D3",
                            DistrictId = 3
                        },
                        new
                        {
                            CityId = 10,
                            CityName = "City -2-D3",
                            DistrictId = 3
                        },
                        new
                        {
                            CityId = 11,
                            CityName = "City -3-D3",
                            DistrictId = 3
                        },
                        new
                        {
                            CityId = 12,
                            CityName = "City -4-D3",
                            DistrictId = 3
                        },
                        new
                        {
                            CityId = 13,
                            CityName = "City -1-D4",
                            DistrictId = 4
                        },
                        new
                        {
                            CityId = 14,
                            CityName = "City -2-D4",
                            DistrictId = 4
                        },
                        new
                        {
                            CityId = 15,
                            CityName = "City -3-D4",
                            DistrictId = 4
                        },
                        new
                        {
                            CityId = 16,
                            CityName = "City -4-D4",
                            DistrictId = 4
                        },
                        new
                        {
                            CityId = 17,
                            CityName = "City -1-D5",
                            DistrictId = 5
                        },
                        new
                        {
                            CityId = 18,
                            CityName = "City -2-D5",
                            DistrictId = 5
                        },
                        new
                        {
                            CityId = 19,
                            CityName = "City -3-D5",
                            DistrictId = 5
                        },
                        new
                        {
                            CityId = 20,
                            CityName = "City -4-D5",
                            DistrictId = 5
                        },
                        new
                        {
                            CityId = 21,
                            CityName = "City -1-D6",
                            DistrictId = 6
                        },
                        new
                        {
                            CityId = 22,
                            CityName = "City -2-D6",
                            DistrictId = 6
                        },
                        new
                        {
                            CityId = 23,
                            CityName = "City -3-D6",
                            DistrictId = 6
                        },
                        new
                        {
                            CityId = 24,
                            CityName = "City -4-D6",
                            DistrictId = 6
                        },
                        new
                        {
                            CityId = 25,
                            CityName = "City -1-D7",
                            DistrictId = 7
                        },
                        new
                        {
                            CityId = 26,
                            CityName = "City -2-D7",
                            DistrictId = 7
                        },
                        new
                        {
                            CityId = 27,
                            CityName = "City -3-D7",
                            DistrictId = 7
                        },
                        new
                        {
                            CityId = 28,
                            CityName = "City -4-D7",
                            DistrictId = 7
                        },
                        new
                        {
                            CityId = 29,
                            CityName = "City -1-D8",
                            DistrictId = 8
                        },
                        new
                        {
                            CityId = 30,
                            CityName = "City -2-D8",
                            DistrictId = 8
                        },
                        new
                        {
                            CityId = 31,
                            CityName = "City -3-D8",
                            DistrictId = 8
                        },
                        new
                        {
                            CityId = 32,
                            CityName = "City -4-D8",
                            DistrictId = 8
                        },
                        new
                        {
                            CityId = 33,
                            CityName = "City -1-D9",
                            DistrictId = 9
                        },
                        new
                        {
                            CityId = 34,
                            CityName = "City -2-D9",
                            DistrictId = 9
                        },
                        new
                        {
                            CityId = 35,
                            CityName = "City -3-D9",
                            DistrictId = 9
                        },
                        new
                        {
                            CityId = 36,
                            CityName = "City -4-D9",
                            DistrictId = 9
                        },
                        new
                        {
                            CityId = 37,
                            CityName = "City -1-D10",
                            DistrictId = 10
                        },
                        new
                        {
                            CityId = 38,
                            CityName = "City -2-D10",
                            DistrictId = 10
                        },
                        new
                        {
                            CityId = 39,
                            CityName = "City -3-D10",
                            DistrictId = 10
                        },
                        new
                        {
                            CityId = 40,
                            CityName = "City -4-D10",
                            DistrictId = 10
                        },
                        new
                        {
                            CityId = 41,
                            CityName = "City -1-D11",
                            DistrictId = 11
                        },
                        new
                        {
                            CityId = 42,
                            CityName = "City -2-D11",
                            DistrictId = 11
                        },
                        new
                        {
                            CityId = 43,
                            CityName = "City -3-D11",
                            DistrictId = 11
                        },
                        new
                        {
                            CityId = 44,
                            CityName = "City -4-D11",
                            DistrictId = 11
                        },
                        new
                        {
                            CityId = 45,
                            CityName = "City -1-D12",
                            DistrictId = 12
                        },
                        new
                        {
                            CityId = 46,
                            CityName = "City -2-D12",
                            DistrictId = 12
                        },
                        new
                        {
                            CityId = 47,
                            CityName = "City -3-D12",
                            DistrictId = 12
                        },
                        new
                        {
                            CityId = 48,
                            CityName = "City -4-D12",
                            DistrictId = 12
                        },
                        new
                        {
                            CityId = 49,
                            CityName = "City -1-D13",
                            DistrictId = 13
                        },
                        new
                        {
                            CityId = 50,
                            CityName = "City -2-D13",
                            DistrictId = 13
                        },
                        new
                        {
                            CityId = 51,
                            CityName = "City -3-D13",
                            DistrictId = 13
                        },
                        new
                        {
                            CityId = 52,
                            CityName = "City -4-D13",
                            DistrictId = 13
                        },
                        new
                        {
                            CityId = 53,
                            CityName = "City -1-D14",
                            DistrictId = 14
                        },
                        new
                        {
                            CityId = 54,
                            CityName = "City -2-D14",
                            DistrictId = 14
                        },
                        new
                        {
                            CityId = 55,
                            CityName = "City -3-D14",
                            DistrictId = 14
                        },
                        new
                        {
                            CityId = 56,
                            CityName = "City -4-D14",
                            DistrictId = 14
                        },
                        new
                        {
                            CityId = 57,
                            CityName = "City -1-D15",
                            DistrictId = 15
                        },
                        new
                        {
                            CityId = 58,
                            CityName = "City -2-D15",
                            DistrictId = 15
                        },
                        new
                        {
                            CityId = 59,
                            CityName = "City -3-D15",
                            DistrictId = 15
                        },
                        new
                        {
                            CityId = 60,
                            CityName = "City -4-D15",
                            DistrictId = 15
                        },
                        new
                        {
                            CityId = 61,
                            CityName = "City -1-D16",
                            DistrictId = 16
                        },
                        new
                        {
                            CityId = 62,
                            CityName = "City -2-D16",
                            DistrictId = 16
                        },
                        new
                        {
                            CityId = 63,
                            CityName = "City -3-D16",
                            DistrictId = 16
                        },
                        new
                        {
                            CityId = 64,
                            CityName = "City -4-D16",
                            DistrictId = 16
                        });
                });

            modelBuilder.Entity("NailApi.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("nl_Customers", (string)null);
                });

            modelBuilder.Entity("NailApi.Models.DistrictMaster", b =>
                {
                    b.Property<int>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistrictId"));

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("DistrictId");

                    b.HasIndex("StateId");

                    b.ToTable("nl_Districts", (string)null);

                    b.HasData(
                        new
                        {
                            DistrictId = 1,
                            DistrictName = "District -1-S1",
                            StateId = 1
                        },
                        new
                        {
                            DistrictId = 2,
                            DistrictName = "District -2-S1",
                            StateId = 1
                        },
                        new
                        {
                            DistrictId = 3,
                            DistrictName = "District -3-S1",
                            StateId = 1
                        },
                        new
                        {
                            DistrictId = 4,
                            DistrictName = "District -4-S1",
                            StateId = 1
                        },
                        new
                        {
                            DistrictId = 5,
                            DistrictName = "District -1-S2",
                            StateId = 2
                        },
                        new
                        {
                            DistrictId = 6,
                            DistrictName = "District -2-S2",
                            StateId = 2
                        },
                        new
                        {
                            DistrictId = 7,
                            DistrictName = "District -3-S2",
                            StateId = 2
                        },
                        new
                        {
                            DistrictId = 8,
                            DistrictName = "District -4-S2",
                            StateId = 2
                        },
                        new
                        {
                            DistrictId = 9,
                            DistrictName = "District -1-S3",
                            StateId = 3
                        },
                        new
                        {
                            DistrictId = 10,
                            DistrictName = "District -2-S3",
                            StateId = 3
                        },
                        new
                        {
                            DistrictId = 11,
                            DistrictName = "District -3-S3",
                            StateId = 3
                        },
                        new
                        {
                            DistrictId = 12,
                            DistrictName = "District -4-S3",
                            StateId = 3
                        },
                        new
                        {
                            DistrictId = 13,
                            DistrictName = "District -1-S4",
                            StateId = 4
                        },
                        new
                        {
                            DistrictId = 14,
                            DistrictName = "District -2-S4",
                            StateId = 4
                        },
                        new
                        {
                            DistrictId = 15,
                            DistrictName = "District -3-S4",
                            StateId = 4
                        },
                        new
                        {
                            DistrictId = 16,
                            DistrictName = "District -4-S4",
                            StateId = 4
                        });
                });

            modelBuilder.Entity("NailApi.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("nl_Employees", (string)null);
                });

            modelBuilder.Entity("NailApi.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("nl_OrderItems", (string)null);

                    b.HasData(
                        new
                        {
                            OrderItemId = 1,
                            OrderId = 1,
                            ProductId = 0,
                            ProductName = "Sample Product",
                            ProductPrice = 100.00m,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("NailApi.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryTimeSpan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductSku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("nl_Products", (string)null);
                });

            modelBuilder.Entity("NailApi.Models.StateMaster", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateId"));

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StateId");

                    b.ToTable("nl_States", (string)null);

                    b.HasData(
                        new
                        {
                            StateId = 1,
                            StateName = "Bihar"
                        },
                        new
                        {
                            StateId = 2,
                            StateName = "Uttar Pradesh"
                        },
                        new
                        {
                            StateId = 3,
                            StateName = "Madhya Pradesh"
                        },
                        new
                        {
                            StateId = 4,
                            StateName = "Maharashtra"
                        });
                });

            modelBuilder.Entity("NailApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("nl_Users", (string)null);
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.ToTable("nl_Orders", (string)null);

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            Address = "Noida",
                            CustomerEmail = "test@example.com",
                            CustomerId = 0,
                            CustomerName = "Test User",
                            OrderDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "9877366333",
                            TotalAmount = 200.00m
                        });
                });

            modelBuilder.Entity("NailApi.Models.CityMaster", b =>
                {
                    b.HasOne("NailApi.Models.DistrictMaster", "District")
                        .WithMany("Cities")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("NailApi.Models.DistrictMaster", b =>
                {
                    b.HasOne("NailApi.Models.StateMaster", "State")
                        .WithMany("Districts")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("NailApi.Models.OrderItem", b =>
                {
                    b.HasOne("Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("NailApi.Models.Product", b =>
                {
                    b.HasOne("NailApi.Models.Category", null)
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NailApi.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("NailApi.Models.DistrictMaster", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("NailApi.Models.StateMaster", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
